export const SET_COLOR_THEME = "SET_COLOR_THEME";
export const SET_DATA_ENVIRONMENT = "SET_DATA_ENVIRONMENT";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const SHOW_MODAL = "SHOW_MODAL";
// Archetype Selector
export const SELECT_ARCHETYPE = "SELECT_ARCHETYPE";
// Character Designer
export const SET_CHARACTER_NAME = "SET_CHARACTER_NAME";
export const SELECT_ORIGIN = "SELECT_ORIGIN";
export const SELECT_PRIMARY_POWERSET = "SELECT_PRIMARY_POWERSET";
export const SELECT_SECONDARY_POWERSET = "SELECT_SECONDARY_POWERSET";
export const SELECT_POWER = "SELECT_POWER";
export const ADD_SLOT_TO_POWER = "ADD_SLOT_TO_POWER";
export const APPLY_ENHANCEMENT_TO_POWER = "APPLY_ENHANCEMENT_TO_POWER";

export const PAGE_MAIN_MENU = 0;
export const PAGE_SELECT_ARCHETYPE = 1;
export const PAGE_CHARACTER_DESIGNER = 2;

export const MODAL_HIDE = 0;
export const MODAL_LEAVE_DESIGNER = 1;
export const MODAL_SELECT_POWER = 2;
export const MODAL_ENHANCE_POWER = 3;