export const SET_COLOR_THEME = "SET_COLOR_THEME";
export const SET_DATA_ENVIRONMENT = "SET_DATA_ENVIRONMENT";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const SELECT_ARCHETYPE = "SELECT_ARCHETYPE";

export const PAGE_MAIN_MENU = 0;
export const PAGE_SELECT_ARCHETYPE = 1;
export const PAGE_CHARACTER_DESIGNER = 2;